name: Main Build Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.0'
      - name: Check
        run: |
          make vet
          make test
      - name: Run build
        run: |
          make build-ci
      - name: Deploy DO
        env:
          DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          DO_APP_ID: ${{ secrets.DO_APP_ID }}
        run: ./.github/scripts/deploy-do.sh
